# Configuraci贸n del servidor
server:
  port: 8085

# Configuraci贸n de la base de datos
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta-PlazaComidas
    username: postgres
    password: dan34981
  jpa:
    hibernate:
      ddl-auto: update

# Configuraci贸n de Feign Client
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

# Configuraci贸n del microservicio de usuarios
users-service:
  url: http://localhost:8080
